version: '3.4'

networks:
  dbgpproxy:
    external:
      name: dbgpproxy_dbgpproxy
  proxy:
    external:
      name: proxy_proxy
  dhr:

services:
  dhr_apache:
    build:
      context: ../../../${DP_DOMAIN}/src/dhr
      dockerfile: Dockerfile.apache
      args:
        PACKAGES_DEV: ${DP_PACKAGES_DEV-rsync vim} rsync ${PACKAGES_DEV-}
        GITHUB_OAUTH_TOKEN: ${GITHUB_OAUTH_TOKEN-""}
    depends_on:
      - dhr_mysql
    extra_hosts:
      - "elasticsearch_090:${DP_DATASOURCES_IP-192.168.251.3}"
      - "elasticsearch_14:${DP_DATASOURCES_IP-192.168.251.3}"
      - "elasticsearch_53:${DP_DATASOURCES_IP-192.168.251.3}"
      - "mysql_main:${DP_DATASOURCES_IP-192.168.251.3}"
      - "mysql_sps:${DP_DATASOURCES_IP-192.168.251.3}"
    image: registry.developer-portal.test/dhr/php-5.6.36-apache-jessie:${DP_DOCKER_IMAGE_TAG-latest}
    labels:
      com.aramisauto.developer-portal.default: "true"
      com.aramisauto.developer-portal.shell: /bin/bash
      com.aramisauto.developer-portal.logs: "" # https://github.com/ARAMISAUTO/developer-portal/blob/master/README.md#service-logs
      com.aramisauto.developer-portal.username: app
      com.dnsdock.alias: dhr.${DP_DOMAIN},apache.dhr.${DP_DOMAIN}
      com.dnsdock.ip_addr: "172.28.1.1"
      traefik.enable: "true"
      traefik.backend: dhr_apache
      traefik.frontend.rule: "Host:dhr.${DP_DOMAIN},apache.dhr.${DP_DOMAIN}"
      traefik.docker.network: proxy_proxy
    networks:
      - dbgpproxy
      - proxy
      - dhr
    volumes:
      - type: bind
        source: ../../src/dhr
        target: /mnt/app
      - ./etc/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./etc/php.apache.ini:/usr/local/etc/php/php.ini
      - ~/.composer:/home/app/.composer
      - ~/.ssh:/home/app/.ssh
    working_dir: /mnt/app

  dhr_mysql:
    environment:
      MYSQL_DATABASE: dhr
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5
    networks:
        - dhr
    volumes:
      - ../../src/dhr/src/data/fixtures/net_dahearditrecords_www.dump.sql:/docker-entrypoint-initdb.d/net_dahearditrecords_www.dump.sql
