version: '3'

networks:
  dbgp-proxy:
    external:
      name: dbgpproxy_dbgp-proxy
  proxy:
    external:
      name: proxy_proxy
  daheardit:

services:
  daheardit_apache:
    build:
      context: ../../../${DP_DOMAIN}/src/daheardit
      args:
        # PACKAGES_DEV: ${DP_PACKAGES_DEV-rsync vim} rsync ${PACKAGES_DEV-}
        PACKAGES_DEV: rsync
        GITHUB_OAUTH_TOKEN: ${GITHUB_OAUTH_TOKEN-""}
    depends_on:
      - daheardit_mysql
    extra_hosts:
      - "elasticsearch_090:${DP_DATASOURCES_IP-192.168.251.3}"
      - "elasticsearch_14:${DP_DATASOURCES_IP-192.168.251.3}"
      - "elasticsearch_53:${DP_DATASOURCES_IP-192.168.251.3}"
      - "mysql_main:${DP_DATASOURCES_IP-192.168.251.3}"
      - "mysql_sps:${DP_DATASOURCES_IP-192.168.251.3}"
    image: constructionsincongrues/daheardit-php-5.6.36-apache-jessie:${DP_IMAGE_TAG-latest}
    labels:
      com.aramisauto.developer-portal.default: "true"
      com.aramisauto.developer-portal.dependencies: "dbgp-proxy"
      com.aramisauto.developer-portal.shell: /bin/bash
      com.aramisauto.developer-portal.logs: "" # https://github.com/ARAMISAUTO/developer-portal/blob/master/README.md#service-logs
      com.aramisauto.developer-portal.username: app
      com.dnsdock.alias: daheardit.${DP_DOMAIN}${DP_DOMAIN_SUFFIX},apache.daheardit.${DP_DOMAIN}${DP_DOMAIN_SUFFIX}
      com.dnsdock.ip_addr: "172.28.1.1"
      traefik.enable: "true"
      traefik.backend: daheardit_apache
      traefik.frontend.rule: "Host:daheardit.${DP_DOMAIN}${DP_DOMAIN_SUFFIX},apache.daheardit.${DP_DOMAIN}${DP_DOMAIN_SUFFIX}"
      traefik.docker.network: proxy_proxy
    networks:
      - dbgp-proxy
      - proxy
      - daheardit
    volumes:
      - ../../src/daheardit:/mnt/app
      - ./etc/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./etc/php.apache.ini:/usr/local/etc/php/php.ini
      - ~/.composer:/home/app/.composer
      - ~/.ssh:/home/app/.ssh
    working_dir: /mnt/app

  daheardit_mysql:
    environment:
      MYSQL_DATABASE: daheardit
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5
    networks:
        - daheardit
    volumes:
      - ../../src/daheardit/src/data/fixtures/net_dahearditrecords_www.dump.sql:/docker-entrypoint-initdb.d/net_dahearditrecords_www.dump.sql
