version: '3.4'

networks:
  dbgpproxy:
    external:
      name: dbgpproxy_dbgpproxy
  proxy:
    external:
      name: proxy_proxy
  urlinfo:

services:
  urlinfo_apache:
    build:
      context: ../../../${DP_DOMAIN}/src/urlinfo
      dockerfile: Dockerfile.apache
      args:
        PACKAGES_DEV: ${DP_PACKAGES_DEV-rsync vim} rsync ${PACKAGES_DEV-}
        GITHUB_OAUTH_TOKEN: ${GITHUB_OAUTH_TOKEN-""}
    image: registry.developer-portal.test/urlinfo/php-7.2.3-apache-jessie:${DP_DOCKER_IMAGE_TAG-latest}
    labels:
      com.aramisauto.developer-portal.default: "true"
      com.aramisauto.developer-portal.shell: /bin/bash
      com.aramisauto.developer-portal.logs: "" # https://github.com/ARAMISAUTO/developer-portal/blob/master/README.md#service-logs
      com.aramisauto.developer-portal.username: app
      com.dnsdock.alias: urlinfo.${DP_DOMAIN},apache.urlinfo.${DP_DOMAIN}
      com.dnsdock.ip_addr: "172.28.1.1"
      traefik.enable: "true"
      traefik.backend: urlinfo_apache
      traefik.frontend.rule: "Host:urlinfo.${DP_DOMAIN},apache.urlinfo.${DP_DOMAIN}"
      traefik.docker.network: proxy_proxy
    networks:
      - dbgpproxy
      - proxy
      - urlinfo
    volumes:
      - type: bind
        source: ../../src/urlinfo
        target: /mnt/app
      - ./etc/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./etc/php.apache.ini:/usr/local/etc/php/php.ini
      - ~/.composer:/home/app/.composer
      - ~/.ssh:/home/app/.ssh
    working_dir: /mnt/app