site_name: "Developer Portal Domain : incongru.test"
theme:
  name: 'material'
markdown_extensions:
  - admonition
  - codehilite
plugins:
  - awesome-pages
  - search
repo_name: GitHub
repo_url: https://github.com/constructions-incongrues/developer-portal-domain/
edit_uri: edit/master/docs/fr/docs
strict: true